import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers"; // ★ 추가: 방금 만든 Providers 불러오기

// Giants 폰트 설정
const giants = localFont({
  src: [
    {
      path: "../../public/fonts/Giants-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Giants-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-giants", // CSS 변수명 정의
});

export const metadata: Metadata = {
  title: "DUTCH TRIP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${giants.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* ★ 추가: 앱 전체(children)를 Providers로 감싸주기 */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}